/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about/About.vue')['default']
    AboutCard: typeof import('./src/components/about/AboutCard.vue')['default']
    Alert: typeof import('./src/components/shared/Alert.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    DialogDelete: typeof import('./src/components/dialogs/DialogTaskDelete.vue')['default']
    DialogTaskDelete: typeof import('./src/components/dialogs/DialogTaskDelete.vue')['default']
    DialogTaskFields: typeof import('./src/components/dialogs/DialogTaskFields.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListTasks: typeof import('./src/components/ListTasks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToDoList: typeof import('./src/components/ToDoList.vue')['default']
  }
}
